const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  getChangelog: () => ipcRenderer.invoke("get-changelog"),
  getSettings: () => ipcRenderer.invoke("get-settings"),
  saveSettings: (s) => ipcRenderer.invoke("save-settings", s),
  getSounds: () => ipcRenderer.invoke("get-sounds"),
  pickFolder: () => ipcRenderer.invoke("pick-folder"),
  switchFolder: (path) => ipcRenderer.invoke("switch-folder", path),
  removeFolder: (path) => ipcRenderer.invoke("remove-folder", path),
  checkFileExists: (path) => ipcRenderer.invoke("check-file-exists", path),
  pickImage: () => ipcRenderer.invoke("pick-image"),
  readSoundFile: (filePath) => ipcRenderer.invoke("read-sound-file", filePath),
  onWsPlaySound: (callback) => ipcRenderer.on("ws-play-sound", (_event, data) => callback(data)),
  onWsStopAll: (callback) => ipcRenderer.on("ws-stop-all", () => callback()),
  updatePlayingStatus: (keys) => ipcRenderer.send("ws-playing-status", keys),
  installStreamDeckPlugin: () => ipcRenderer.invoke("install-streamdeck-plugin"),
  getStreamDeckPluginStatus: () => ipcRenderer.invoke("get-streamdeck-plugin-status"),
  windowMinimize: () => ipcRenderer.send("window-minimize"),
  windowMaximize: () => ipcRenderer.send("window-maximize"),
  windowClose: () => ipcRenderer.send("window-close"),
  windowIsMaximized: () => ipcRenderer.invoke("window-is-maximized"),
  onWindowMaximized: (cb) => ipcRenderer.on("window-maximized", (_event, val) => cb(val)),
  openExternal: (url) => ipcRenderer.send("open-external", url),
});
