const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  getChangelog: () => ipcRenderer.invoke("get-changelog"),
  getSettings: () => ipcRenderer.invoke("get-settings"),
  saveSettings: (s) => ipcRenderer.invoke("save-settings", s),
  getSounds: () => ipcRenderer.invoke("get-sounds"),
  pickFolder: () => ipcRenderer.invoke("pick-folder"),
  switchFolder: (path) => ipcRenderer.invoke("switch-folder", path),
  removeFolder: (path) => ipcRenderer.invoke("remove-folder", path),
  checkFileExists: (path) => ipcRenderer.invoke("check-file-exists", path),
  trashSoundFile: (path) => ipcRenderer.invoke("trash-sound-file", path),
  pickImage: () => ipcRenderer.invoke("pick-image"),
  readSoundFile: (filePath) => ipcRenderer.invoke("read-sound-file", filePath),
  onWsPlaySound: (callback) => ipcRenderer.on("ws-play-sound", (_event, data) => callback(data)),
  onWsStopAll: (callback) => ipcRenderer.on("ws-stop-all", () => callback()),
  onWsSaveClip: (callback) => ipcRenderer.on("ws-save-clip", () => callback()),
  onWsOpenShadowSettings: (callback) => ipcRenderer.on("ws-open-shadow-settings", () => callback()),
  onGlobalPlaySound: (callback) => ipcRenderer.on("global-play-sound", (_event, data) => callback(data)),
  onGlobalSaveClip: (callback) => ipcRenderer.on("global-save-shadow-clip", () => callback()),
  onGlobalStopAll: (callback) => ipcRenderer.on("global-stop-all", () => callback()),
  pickClipsFolder: () => ipcRenderer.invoke("pick-clips-folder"),
  saveShadowClip: (data, folder) => ipcRenderer.invoke("save-shadow-clip", data, folder),
  listClipsFolder: (folder) => ipcRenderer.invoke("list-clips-folder", folder),
  trashClipFile: (path) => ipcRenderer.invoke("trash-clip-file", path),
  revealInExplorer: (folderPath) => ipcRenderer.invoke("reveal-in-explorer", folderPath),
  saveExportedClip: (data, destFolder, filename) => ipcRenderer.invoke("save-exported-clip", data, destFolder, filename),
  updatePlayingStatus: (keys) => ipcRenderer.send("ws-playing-status", keys),
  installStreamDeckPlugin: () => ipcRenderer.invoke("install-streamdeck-plugin"),
  getStreamDeckPluginStatus: () => ipcRenderer.invoke("get-streamdeck-plugin-status"),
  windowMinimize: () => ipcRenderer.send("window-minimize"),
  windowMaximize: () => ipcRenderer.send("window-maximize"),
  windowClose: () => ipcRenderer.send("window-close"),
  windowIsMaximized: () => ipcRenderer.invoke("window-is-maximized"),
  onWindowMaximized: (cb) => ipcRenderer.on("window-maximized", (_event, val) => cb(val)),
  openExternal: (url) => ipcRenderer.send("open-external", url),
});
