/* This file is auto-generated by the iconsToCSS module; do not edit */

export type IconName =
  | 'arrow-rotate-right'
  | 'circle-question'
  | 'eye-slash'
  | 'eye'
  | 'folder-open'
  | 'grid-2'
  | 'grid-4'
  | 'pencil'
  | 'plus'
  | 'stop'
  | 'triangle-exclamation'
  | 'window-maximize'
  | 'window-restore'
  | 'xmark'
  | 'chevron-down-light'
  | 'arrow-rotate-right-rrr'
  | 'chevron-down-rrr'
  | 'circle-question-rrr'
  | 'ellipsis-rrr'
  | 'eye-slash-rrr'
  | 'eye-rrr'
  | 'folder-open-rrr'
  | 'gear-rrr'
  | 'grid-2-rrr'
  | 'headphones-simple-rrr'
  | 'plus-rrr'
  | 'stop-rrr'
  | 'triangle-exclamation-rrr'
  | 'window-maximize-rrr'
  | 'window-minimize-rrr'
  | 'window-restore-rrr'
  | 'xmark-rrr'
  | 'chevron-down-solid'
  | 'ellipsis-solid'
  | 'gear-solid'
  | 'headphones-simple-solid'
  | 'microphone-solid'
  | 'pencil-solid'
  | 'scissors-solid'
  | 'window-minimize-solid'
  | 'xmark-solid'

export const IconsFolder = [
  'duotone',
  'light',
  'rrr',
  'solid',
]
